
vbus-proxy-objs += bus-proxy.o
obj-$(CONFIG_VBUS_PROXY) += vbus-proxy.o

vbus-pcibridge-objs += pci-bridge.o
obj-$(CONFIG_VBUS_PCIBRIDGE) += vbus-pcibridge.o

vbus-ioq-test-objs += ioq-test.o
obj-$(CONFIG_VBUS_IOQ_TEST) += vbus-ioq-test.o

